#version: '3.8'

services:
  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: matthias
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "echo hello"] # fake check
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - todonet

  todobackend:
    image: todobackend:v24
    container_name: todobackend
    ports:
      - "8080:8080"
    networks:
      - todonet
    restart: always
    depends_on:
      postgresdb:
        condition: service_healthy

  todoui:
    image: todoui:v24
    container_name: todoui
    ports:
      - "8090:8090"
    networks:
      - todonet
    restart: always

networks:
  todonet:
    driver: bridge

volumes:
  postgresdata: