apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backendspringboot
  name: backendspringboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backendspringboot
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backendspringboot
    spec:
      containers:
      - image: maeddes/backendspringboot:hse24patch
        name: backendspringboot
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /hello
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 1
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://shoppingdb:5432/shoppingdb