apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backendspringboot
  name: backendspringboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendspringboot
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backendspringboot
    spec:
      containers:
      - image: maeddes/backendspringboot:hse24
        name: backendspringboot
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://shoppingdb:5432/shoppingdb